### ISSUE TITLE
python3.6 order (MRO) for bases type, GenericMeta, _DataPipeMeta

### ISSUE THREAD

**Issue by siriusa51** [szymonmaszke/torchdata#32]
```
Traceback (most recent call last):
  File "test-dataset.py", line 1, in <module>
    from dataset import func
  File "/root/torch-cache-test/dataset/func.py", line 3, in <module>
    from . import nocache
  File "/root/torch-cache-test/dataset/nocache.py", line 1, in <module>
    from . import utils
  File "/root/torch-cache-test/dataset/utils.py", line 8, in <module>
    import torchdatasets as td
  File "/opt/conda/lib/python3.6/site-packages/torchdatasets/__init__.py", line 60, in <module>
    from . import cachers, datasets, maps, modifiers, samplers
  File "/opt/conda/lib/python3.6/site-packages/torchdatasets/datasets.py", line 164, in <module>
    class MetaIterableWrapper(MetaIterable, GenericMeta, _typing._DataPipeMeta): pass
TypeError: Cannot create a consistent method resolution
order (MRO) for bases type, GenericMeta, _DataPipeMeta
```

**Comment by sissiyang** [comment]
i have the same issue
